In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df23 = pd.read_csv('TLE2023_ML_Ready.csv')
df24 = pd.read_csv('TLE2024_ML_Ready.csv')
df25 = pd.read_csv('TLE2025_ML_Ready.csv')

full_tle = pd.concat([df23, df24, df25], ignore_index=True)

In [3]:
df23.tail()

,Uydu_Ismi,TLE_Line1,TLE_Line2,Surtunme_Katsayisi_BStar,Yorunge_Egilimi_Inclo,Dismerkezlik_Ecco,Ortalama_Hareket_NoKozai
15737154,Bilinmeyen Uydu,1 58223U 23170T 23365.74266699 .00000443 0...,2 58223 42.9983 217.4575 0001224 269.3558 90...,0.000048,0.750462,0.000122,0.065560
15737155,Bilinmeyen Uydu,1 58400U 23179A 23365.80069640 .00005210 0...,2 58400 97.4251 250.0476 0016952 132.3983 227...,0.000232,1.700389,0.001695,0.066397
15737156,Bilinmeyen Uydu,1 58555U 23193C 23365.77538872 .00012519 0...,2 58555 97.2586 10.0893 0020824 183.8107 176...,0.000317,1.697483,0.002082,0.067179
15737157,Bilinmeyen Uydu,1 58692U 23212B 23365.88689859 -.00000146 0...,2 58692 49.9992 61.5162 0005167 291.0812 215...,0.000000,0.872651,0.000517,0.060592
15737158,Bilinmeyen Uydu,1 49318U 21091D 23365.96617102 -.00004498 0...,2 49318 97.4294 185.7783 0004544 324.3612 198...,-0.002056,1.700464,0.000454,0.062009

In [4]:
df23.columns

Index(['Uydu_Ismi', 'TLE_Line1', 'TLE_Line2', 'Surtunme_Katsayisi_BStar',
       'Yorunge_Egilimi_Inclo', 'Dismerkezlik_Ecco',
       'Ortalama_Hareket_NoKozai'],
      dtype='object')

In [5]:
df23.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15737159 entries, 0 to 15737158
Data columns (total 7 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Uydu_Ismi                 object
 1   TLE_Line1                 object
 2   TLE_Line2                 object
 3   Surtunme_Katsayisi_BStar  float64
 4   Yorunge_Egilimi_Inclo     float64
 5   Dismerkezlik_Ecco         float64
 6   Ortalama_Hareket_NoKozai  float64
dtypes: float64(4), object(3)
memory usage: 840.5+ MB

In [6]:
df24.columns

Index(['Uydu_Ismi', 'TLE_Line1', 'TLE_Line2', 'Surtunme_Katsayisi_BStar',
       'Yorunge_Egilimi_Inclo', 'Dismerkezlik_Ecco',
       'Ortalama_Hareket_NoKozai'],
      dtype='object')

In [7]:
df25.columns

Index(['Uydu_Ismi', 'TLE_Line1', 'TLE_Line2', 'Surtunme_Katsayisi_BStar',
       'Yorunge_Egilimi_Inclo', 'Dismerkezlik_Ecco',
       'Ortalama_Hareket_NoKozai'],
      dtype='object')

In [8]:
full_tle

,Uydu_Ismi,TLE_Line1,TLE_Line2,Surtunme_Katsayisi_BStar,Yorunge_Egilimi_Inclo,Dismerkezlik_Ecco,Ortalama_Hareket_NoKozai
0,Bilinmeyen Uydu,1 48391U 21038AQ 22365.71710330 .00000836 0...,2 48391 53.0523 166.9021 0001574 65.8859 294...,0.000075,0.925937,0.000157,0.065729
1,Bilinmeyen Uydu,1 32395U 07065C 22365.86863583 .00000051 0...,2 32395 64.3659 234.7531 0016625 4.4172 172...,0.000000,1.123397,0.001662,0.009298
2,Bilinmeyen Uydu,1 48392U 21038AR 22365.77976089 .00000624 0...,2 48392 53.0529 166.6104 0001435 113.0368 247...,0.000061,0.925948,0.000143,0.065729
3,Bilinmeyen Uydu,1 15354U 84108B 22365.96057214 .00804600 3...,2 15354 56.9900 306.7257 0008561 72.6167 287...,0.000736,0.994663,0.000856,0.070334
4,Bilinmeyen Uydu,1 51140U 22005AN 22365.61715979 .00003032 0...,2 51140 53.2168 124.8520 0002906 35.0580 325...,0.000208,0.928808,0.000291,0.065836
...,...,...,...,...,...,...,...
56194575,Bilinmeyen Uydu,1 62827U 25018X 25365.79956237 .01830149 1...,2 62827 53.1578 222.6483 0000549 54.2899 305...,0.004664,0.927779,0.000055,0.069606
56194576,Bilinmeyen Uydu,1 67132U 25300B 25365.84118213 .00055316 3...,2 67132 97.5610 81.0876 0162681 319.8916 39...,0.000242,1.702761,0.016268,0.068399
56194577,Bilinmeyen Uydu,1 15369U 84111A 25365.88028396 .02525725 -1...,2 15369 82.4794 244.6557 0002537 132.0100 228...,0.000695,1.439537,0.000254,0.071037
56194578,Bilinmeyen Uydu,1 47812U 21018AB 25365.93218688 .01535582 1...,2 47812 53.0344 167.7643 0005754 284.3570 75...,0.001323,0.925625,0.000575,0.070385
56194579,Bilinmeyen Uydu,1 48363U 21038L 25365.88335112 .01638932 1...,2 48363 53.0317 201.9979 0008260 222.5542 137...,0.001759,0.925578,0.000826,0.070242

In [9]:
full_tle.drop("Uydu_Ismi", axis=1)

,TLE_Line1,TLE_Line2,Surtunme_Katsayisi_BStar,Yorunge_Egilimi_Inclo,Dismerkezlik_Ecco,Ortalama_Hareket_NoKozai
0,1 48391U 21038AQ 22365.71710330 .00000836 0...,2 48391 53.0523 166.9021 0001574 65.8859 294...,0.000075,0.925937,0.000157,0.065729
1,1 32395U 07065C 22365.86863583 .00000051 0...,2 32395 64.3659 234.7531 0016625 4.4172 172...,0.000000,1.123397,0.001662,0.009298
2,1 48392U 21038AR 22365.77976089 .00000624 0...,2 48392 53.0529 166.6104 0001435 113.0368 247...,0.000061,0.925948,0.000143,0.065729
3,1 15354U 84108B 22365.96057214 .00804600 3...,2 15354 56.9900 306.7257 0008561 72.6167 287...,0.000736,0.994663,0.000856,0.070334
4,1 51140U 22005AN 22365.61715979 .00003032 0...,2 51140 53.2168 124.8520 0002906 35.0580 325...,0.000208,0.928808,0.000291,0.065836
...,...,...,...,...,...,...
56194575,1 62827U 25018X 25365.79956237 .01830149 1...,2 62827 53.1578 222.6483 0000549 54.2899 305...,0.004664,0.927779,0.000055,0.069606
56194576,1 67132U 25300B 25365.84118213 .00055316 3...,2 67132 97.5610 81.0876 0162681 319.8916 39...,0.000242,1.702761,0.016268,0.068399
56194577,1 15369U 84111A 25365.88028396 .02525725 -1...,2 15369 82.4794 244.6557 0002537 132.0100 228...,0.000695,1.439537,0.000254,0.071037
56194578,1 47812U 21018AB 25365.93218688 .01535582 1...,2 47812 53.0344 167.7643 0005754 284.3570 75...,0.001323,0.925625,0.000575,0.070385
56194579,1 48363U 21038L 25365.88335112 .01638932 1...,2 48363 53.0317 201.9979 0008260 222.5542 137...,0.001759,0.925578,0.000826,0.070242

In [10]:
full_tle.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56194580 entries, 0 to 56194579
Data columns (total 7 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Uydu_Ismi                 object
 1   TLE_Line1                 object
 2   TLE_Line2                 object
 3   Surtunme_Katsayisi_BStar  float64
 4   Yorunge_Egilimi_Inclo     float64
 5   Dismerkezlik_Ecco         float64
 6   Ortalama_Hareket_NoKozai  float64
dtypes: float64(4), object(3)
memory usage: 2.9+ GB

In [12]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import joblib

print("🚀 1. Bellekteki 'full_tle' Verisi İşleme Alınıyor...")
df_islem = full_tle.copy()

print("⚙️ 2. Fiziksel Filtreler (LEO Uyduları ve Gerçek Sürtünmeler)...")
df_islem = df_islem[(df_islem['Ortalama_Hareket_NoKozai'] > 0.05) & (df_islem['Surtunme_Katsayisi_BStar'] > 0)]

print("⏱️ 3. Zaman Şifresi (Epoch) Kırılıyor...")
epoch_str = df_islem['TLE_Line1'].astype(str).str[18:32]
yillar = 2000 + epoch_str.str[:2].astype(int)
gunler = epoch_str.str[2:].astype(float)
df_islem['Timestamp'] = pd.to_datetime(yillar, format='%Y') + pd.to_timedelta(gunler - 1, unit='D')
df_islem = df_islem.sort_values('Timestamp')

# ---------------------------------------------------------
print("🌩️ 4. Fırtına Bilgisi (KP_INDEX) Çekiliyor (Offline Çözüm)...")
# İnternetten indirmek yerine mevcut dosyadaki fırtına verilerini kullanıyoruz
df_sahizer = pd.read_csv("Alaz_ABSTAR_Training.csv", usecols=['EPOCH', 'KP_INDEX'])
df_kp = df_sahizer.rename(columns={'EPOCH': 'timestamp', 'KP_INDEX': 'kp_value'}).copy()

df_kp['timestamp'] = pd.to_datetime(df_kp['timestamp'], errors='coerce')
df_kp = df_kp.dropna(subset=['timestamp']).sort_values('timestamp').drop_duplicates(subset=['timestamp'])

# Şahizer Abla'nın dosyasında Kp 8.0 değeri 80.0 olarak kaydedilmiş. Bunu normale (8.0'a) döndürüyoruz.
df_kp['kp_value'] = df_kp['kp_value'] / 10.0
# ---------------------------------------------------------

print("🔗 5. BÜYÜK BİRLEŞME: Ham BSTAR + Şahizer'in KP Verisi Çarpışıyor...")
final_df = pd.merge_asof(df_islem, df_kp, left_on='Timestamp', right_on='timestamp', direction='backward')
final_df = final_df.dropna(subset=['kp_value', 'Surtunme_Katsayisi_BStar'])

print("✂️ 6. AKILLI SEYRELTME (Azure Maliyet Optimizasyonu)...")
firtina_df = final_df[final_df['kp_value'] >= 5.0]
sakin_df = final_df[final_df['kp_value'] < 5.0].sample(frac=0.01, random_state=42)

final_df = pd.concat([firtina_df, sakin_df]).sample(frac=1.0, random_state=42)
print(f"📉 Optimize Edilmiş Nihai Satır Sayısı: {len(final_df)}")

print("🧠 7. ALAZ AI Eğitimi Başlıyor (Random Forest)...")
final_df['BSTAR_MACRO'] = final_df['Surtunme_Katsayisi_BStar'] * 100000

features = ['kp_value', 'Yorunge_Egilimi_Inclo', 'Ortalama_Hareket_NoKozai']
target = 'BSTAR_MACRO'

X = final_df[features]
y = final_df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestRegressor(n_estimators=100, max_depth=12, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred)) 
r2 = r2_score(y_test, y_pred)
basari_yuzdesi = r2 * 100

print("-" * 40)
print(f"📉 Hata Payı (RMSE): {rmse:.4f}")
print(f"🎯 Modelin Açıklanabilirlik (Başarı) Oranı: %{basari_yuzdesi:.2f}")
print("-" * 40)

joblib.dump(model, "solar_flare_model.pkl")
final_df.to_csv("ALAZ_Ultra_Elit_Egitim_Seti.csv", index=False)
print("✅ İşlem Tamam! app.py için beyni hazırladık.")

🚀 1. Bellekteki 'full_tle' Verisi İşleme Alınıyor...
⚙️ 2. Fiziksel Filtreler (LEO Uyduları ve Gerçek Sürtünmeler)...
⏱️ 3. Zaman Şifresi (Epoch) Kırılıyor...
🌩️ 4. Fırtına Bilgisi (KP_INDEX) Çekiliyor (Offline Çözüm)...

FileNotFoundError: [Errno 2] No such file or directory: 'Alaz_ABSTAR_Training.csv'